# pyright: reportUnknownVariableType=false
import json
import re
from io import BytesIO
from zipfile import ZIP_DEFLATED, ZipFile

from generated_app.manifest import BackendContract, analyze_generated_app_html
from generated_app.repair import build_quality_gates, build_repair_prompt


def slugify_app_name(app_name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", app_name.strip().lower()).strip("-")
    return slug or "generated-app"


def _python_string(value: str) -> str:
    return repr(value)


def _endpoint_function_name(contract: BackendContract) -> str:
    route_part = contract.api_route.strip("/").replace("/", "_").replace("-", "_")
    name = re.sub(r"[^A-Za-z0-9_]+", "_", route_part).strip("_")
    if not name:
        name = contract.contract_id.replace("-", "_")
    if name[0].isdigit():
        name = f"endpoint_{name}"
    return name


def _build_backend_main(contracts: list[BackendContract]) -> str:
    lines = [
        "from fastapi import FastAPI",
        "from pydantic import BaseModel",
        "",
        "app = FastAPI(title='Generated App Backend')",
        "submissions: list[dict] = []",
        "",
        "",
        "class Submission(BaseModel):",
        "    data: dict = {}",
        "",
        "",
        "@app.get('/api/health')",
        "def health():",
        "    return {'ok': True}",
        "",
        "",
        "@app.get('/api/fixtures')",
        "def fixtures():",
        "    return {'submissions': submissions}",
        "",
    ]
    for contract in contracts:
        route = _python_string(contract.api_route)
        function_name = _endpoint_function_name(contract)
        lines.extend(
            [
                "",
                f"@app.{contract.method.lower()}({route})",
                f"def {function_name}(submission: Submission):",
                "    record = submission.data",
                "    submissions.append(record)",
                "    return {'ok': True, 'record': record}",
            ]
        )
    return "\n".join(lines) + "\n"


def _build_schema_sql(contracts: list[BackendContract]) -> str:
    statements = [
        "CREATE TABLE IF NOT EXISTS generated_submission (",
        "  id INTEGER PRIMARY KEY AUTOINCREMENT,",
        "  contract_id TEXT NOT NULL,",
        "  payload_json TEXT NOT NULL,",
        "  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP",
        ");",
    ]
    for contract in contracts:
        table_name = re.sub(r"[^a-z0-9_]+", "_", contract.contract_id.lower()).strip("_")
        if table_name.startswith("form"):
            table_name = "evaluation"
        statements.extend(
            [
                "",
                f"CREATE TABLE IF NOT EXISTS {table_name} (",
                "  id INTEGER PRIMARY KEY AUTOINCREMENT,",
                "  payload_json TEXT NOT NULL,",
                "  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP",
                ");",
            ]
        )
    return "\n".join(statements) + "\n"


def _build_smoke_test(contracts: list[BackendContract]) -> str:
    first_route = contracts[0].api_route if contracts else "/api/health"
    return f"""from fastapi.testclient import TestClient

from backend.main import app


def test_health():
    client = TestClient(app)
    assert client.get('/api/health').json() == {{'ok': True}}


def test_fixture_backed_submission():
    client = TestClient(app)
    response = client.post({first_route!r}, json={{'data': {{'athleteName': 'Jordan'}}}})
    assert response.status_code == 200
    assert response.json()['ok'] is True
"""


def _build_readme(app_name: str) -> str:
    return f"""# {app_name}

Generated by Screenshot-to-Code Factory mirror mode.

## Run the backend

```bash
cd backend
pip install fastapi uvicorn pytest httpx
uvicorn main:app --reload
```

## Run smoke tests

```bash
pytest backend/tests/test_smoke.py
```

The backend is fixture-backed. Endpoints are generated from visible forms and action contracts in the mirrored website.
"""


def build_generated_app_export(code: str, app_name: str = "generated-app") -> bytes:
    slug = slugify_app_name(app_name)
    manifest = analyze_generated_app_html(code)
    gates = build_quality_gates(manifest)
    fixtures = {
        "routes": [route.model_dump(by_alias=True) for route in manifest.routes],
        "assets": [asset.model_dump(by_alias=True) for asset in manifest.assets],
        "submissions": [],
    }

    output = BytesIO()
    with ZipFile(output, "w", ZIP_DEFLATED) as archive:
        archive.writestr(f"{slug}/frontend/index.html", code)
        archive.writestr(f"{slug}/backend/main.py", _build_backend_main(manifest.backend_contracts))
        archive.writestr(f"{slug}/backend/fixtures.json", json.dumps(fixtures, indent=2))
        archive.writestr(f"{slug}/backend/schema.sql", _build_schema_sql(manifest.backend_contracts))
        archive.writestr(f"{slug}/backend/tests/test_smoke.py", _build_smoke_test(manifest.backend_contracts))
        archive.writestr(f"{slug}/manifest.json", json.dumps(manifest.model_dump(by_alias=True), indent=2))
        archive.writestr(
            f"{slug}/quality-gates.json",
            json.dumps([gate.model_dump(by_alias=True) for gate in gates], indent=2),
        )
        archive.writestr(
            f"{slug}/repair-prompt.md",
            build_repair_prompt(manifest, gates),
        )
        archive.writestr(f"{slug}/README.md", _build_readme(app_name))
    return output.getvalue()
